services:
  # Database Services
  customer-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: customer_db
      MYSQL_USER: customer_db_admin
      MYSQL_PASSWORD: customer_db_admin_password
      MYSQL_ROOT_PASSWORD: customer_db_admin_password
    ports:
      - "3306:3306"
    networks:
      - app-network
    profiles:
      - database

  product-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: product_db_admin
      MYSQL_PASSWORD: product_db_admin_password
      MYSQL_ROOT_PASSWORD: product_db_admin_password
    ports:
      - "3307:3306"
    networks:
      - app-network
    profiles:
      - database

  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    profiles:
      - server
    networks:
      - app-network

  # Application services
  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - customer-db
      - eureka-server
    networks:
      - app-network
    environment:
      DATASOURCE_CUSTOMER_URL: jdbc:mysql://customer-db:3306/customer_db
      DATASOURCE_CUSTOMER_USERNAME: customer_db_admin
      DATASOURCE_CUSTOMER_PASSWORD: customer_db_admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
    profiles:
      - app

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - product-db
      - eureka-server
    networks:
      - app-network
    environment:
      DATASOURCE_PRODUCT_URL: jdbc:mysql://product-db:3306/product_db
      DATASOURCE_PRODUCT_USERNAME: product_db_admin
      DATASOURCE_PRODUCT_PASSWORD: product_db_admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
    profiles:
      - app

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - product-db
      - eureka-server
    networks:
      - app-network
    environment:
      DATASOURCE_INVENTORY_URL: jdbc:mysql://product-db:3306/product_db
      DATASOURCE_INVENTORY_USERNAME: product_db_admin
      DATASOURCE_INVENTORY_PASSWORD: product_db_admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
    profiles:
      - app
networks:
  app-network: