services:
  # Database Services

  # Cart service database
  cart-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cart_db
      MYSQL_USER: cart_db_admin
      MYSQL_PASSWORD: cart_db_admin_password
      MYSQL_ROOT_PASSWORD: cart_db_admin_password
    ports:
      - "3308:3306"
    volumes:
      - cart_db_data:/var/lib/mysql

  # Customer service database
  customer-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: customer_db
      MYSQL_USER: customer_db_admin
      MYSQL_PASSWORD: customer_db_admin_password
      MYSQL_ROOT_PASSWORD: customer_db_admin_password
    ports:
      - "3306:3306"
    volumes:
      - customer_db_data:/var/lib/mysql

  # Product service database
  product-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: product_db_admin
      MYSQL_PASSWORD: product_db_admin_password
      MYSQL_ROOT_PASSWORD: product_db_admin_password
    ports:
      - "3307:3306"
    volumes:
      - product_db_data:/var/lib/mysql

  # Spring Cloud Netflix Eureka
  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  # Spring Cloud Gateway
  gateway:
    image: gateway
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - product-service
      - inventory-service
      - customer-service
      - keycloak-service

  # Application services

  # Customer service
  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - customer-db
      - keycloak
      - kafka
      - eureka-server
    environment:
      DATASOURCE_CUSTOMER_URL: jdbc:mysql://customer-db:3306/customer_db
      DATASOURCE_CUSTOMER_USERNAME: customer_db_admin
      DATASOURCE_CUSTOMER_PASSWORD: customer_db_admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Cart service
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - cart-db
      - keycloak-service
      - keycloak
      - kafka
      - eureka-server
    environment:
      DATASOURCE_CART_URL: jdbc:mysql://cart-db:3306/cart_db
      DATASOURCE_CART_USERNAME: cart_db_admin
      DATASOURCE_CART_PASSWORD: cart_db_admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Product service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - product-db
      - keycloak-service
      - keycloak
      - kafka
      - eureka-server
    environment:
      DATASOURCE_PRODUCT_URL: jdbc:mysql://product-db:3306/product_db
      DATASOURCE_PRODUCT_USERNAME: product_db_admin
      DATASOURCE_PRODUCT_PASSWORD: product_db_admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  # Inventory service
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - product-db
      - product-service
      - keycloak-service
      - keycloak
      - kafka
      - eureka-server
    environment:
      DATASOURCE_INVENTORY_URL: jdbc:mysql://product-db:3306/product_db
      DATASOURCE_INVENTORY_USERNAME: product_db_admin
      DATASOURCE_INVENTORY_PASSWORD: product_db_admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on:
      - zookeeper

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
      - "9090:8080"
    depends_on:
      - kafka

  # Keycloak database
  keycloak-db:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
    ports:
      - "8090:8080"
    depends_on:
      - keycloak-db

  # Keycloak Service
  keycloak-service:
    build:
      context: ./keycloak-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      PRODUCT_SERVICE_CLIENT_ID: product-service-client
      PRODUCT_SERVICE_CLIENT_SECRET: product-service-client-secret
      CUSTOMER_SERVICE_CLIENT_ID: customer-service-client
      CUSTOMER_SERVICE_CLIENT_SECRET: customer-service-client-secret
      INVENTORY_SERVICE_CLIENT_ID: inventory-service-client
      INVENTORY_SERVICE_CLIENT_SECRET: inventory-service-client-secret
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - keycloak
      - kafka
      - eureka-server

volumes:
  product_db_data:
  customer_db_data:
  cart_db_data:
  keycloak-db-data:

