# Server Configuration
server:
  port: 8086  # Port where the server will run

# Spring Application Name
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: order-service  # Name of the Spring application

  # Keycloak configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ecommerce/protocol/openid-connect/certs

  # Datasource Configuration for MySQL
  datasource:
    order:
      driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC driver class name
      url: jdbc:mysql://order-db:3309/order_db  # URL of the MySQL database
      username: order_db_admin  # Username for the MySQL database
      password: order_db_admin_password  # Password for the MySQL database

  # JPA Configuration
  jpa:
    generate-ddl: true  # Automatically generate database schema
    hibernate:
      ddl-auto: update  # Update the database schema on startup
    show-sql: true  # Show SQL statements in the logs

  # Kafka Configuration
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}  # Kafka bootstrap servers
      group-id: order_service_group  # Kafka consumer group ID
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Eureka server URL
  instance:
    prefer-ip-address: true  # Prefer IP address for the Eureka instance

# Swagger Configuration
springdoc:
  api-docs:
    path: /orders/v3/api-docs  # Path for API documentation
  swagger-ui:
    path: /orders/swagger-ui.html  # Path for Swagger UI


