# Server Configuration
server:
  port: 8085  # Port where the server will run

# Spring Application Configuration
spring:
  application:
    name: cart-service  # Name of the Spring application
  # Keycloak Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ecommerce/protocol/openid-connect/certs

  # Datasource Configuration for MySQL
  datasource:
    cart:
      driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC driver class name
      url: jdbc:mysql://customer-db:3308/cart_db  # URL of the MySQL database
      username: cart_db_admin  # Username for the MySQL database
      password: cart_db_admin_password  # Password for the MySQL database

  # JPA Configuration
  jpa:
    generate-ddl: true  # Automatically generate database schema
    hibernate:
      ddl-auto: update  # Update the database schema on startup
    show-sql: true  # Show SQL statements in the logs

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}  # Kafka bootstrap servers

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Eureka server URL
  instance:
    prefer-ip-address: true  # Prefer IP address for the Eureka instance

# Springdoc Configuration
springdoc:
  api-docs:
    path: /cart/v3/api-docs  # Path for API documentation
  swagger-ui:
    path: /cart/swagger-ui.html  # Path for Swagger UI

